
type Mutation {
  login(email: String, password: String): String,
  register(email: String!, name: String!, password: String!, confirm_password: String!): String,
  createRoom: Room,
  addUserToRoom(id: ID!, user_id: ID!): Room,
  createMessage(room_id: ID!, message: String!): Boolean,
  createAttachment(room_id: ID!, files: [Upload!]!): Boolean,
  generateClientToken(access_key: String!,email: String!, name: String!): String,
  widgetLogin(access_key: String!, token: String!): User
}